processes:
  FeMgSmectite:
    name: T1250_FeMgSmectite
    path: # \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters
    thresholds:
      median:
        run: True
        size: 3
        iterations: 1
      parameters:
        D2300:
        - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_D2300.IMG
        - [0.001, 0.005, 0.01]
        BD1900_2:
        - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_BD1900_2.IMG
        - [0.01, 0.015, 0.02]
      masks:
        BD1500_2:
        - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_BD1500_2.IMG
        - [0.005]
    pipeline:
    - task: majority
      iterations: 2

    - task: boundary
      iterations: 2
      size: 3

    - task: sieve
      iterations: 1

    - task: open
      iterations: 1
    vectorization:
      driver: ESRI Shapefile
      cs: GCS # PCS or GCS
      stats: ['median', "area", "mean", "std", "min", "max", '25p', '75p']
      output_dict: \\lasp-store\home\taja6898\Documents\Code\mineral-mapping\outputs

  PolySulfate:
    name: T1250_PolySulfate
    path: # \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters
    thresholds:
      median:
        run: True
        size: 3
      iterations: 1
      parameters:
        SINDEX2:
          - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_SINDEX2.IMG
          - [0.01, 0.015, 0.02]
        BD1900_2:
          - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_BD1900_2.IMG
          - [0.012, 0.015, 0.017]
      masks:
        BD1500_2:
          - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_BD1500_2.IMG
          - [0.005]
        BD2100_2:
          - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_BD2100_2.IMG
          - [0.01]
    pipeline:
      - task: majority
        iterations: 2
      - task: boundary
        iterations: 2
        size: 3
      - task: sieve
        iterations: 1
      - task: open
        iterations: 1
    vectorization:
      driver: ESRI Shapefile
      output_dict: \\lasp-store\home\taja6898\Documents\Code\mineral-mapping\outputs

  MonoSulfate:
    name: T1250_MonoSulfate
    path: # \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters
    thresholds:
      median:
        run: True
        size: 3
        iterations: 1
      parameters:
        SINDEX2:
          - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_SINDEX2.IMG
          - [0.025, 0.035, 0.05]
        BD2100_2:
          - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_BD2100_2.IMG
          - [0.01, 0.025, 0.05]
      masks:
        BD1500_2:
          - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_BD1500_2.IMG
          - [0.005]
        BD1900_2:
          - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_BD1900_2.IMG
          - [0.012]
    pipeline:
      - task: majority
        iterations: 2
      - task: boundary
        iterations: 2
        size: 3
      - task: sieve
        iterations: 1
      - task: open
        iterations: 1
    vectorization:
      driver: ESRI Shapefile
      # stats: ['median', "area", "mean", "std", "min", "max", '25p', '75p']
      output_dict: \\lasp-store\home\taja6898\Documents\Code\mineral-mapping\outputs

  Parameter:
    name: MC13_SINDEX2_72_60_70_80
    path: # \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters
    thresholds:
      median:
        run: True
        size: 3
        iterations: 1
      parameters:
        SINDEX2:
          # - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_SINDEX2.IMG
          - \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_BAL1_EQU_IMP_SINDEX2.IMG
          # - \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_BAL1_EQU_IMP_D2300.IMG
          # - \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_BAL1_EQU_IMP_D2300_MOS_IMP.IMG
          # - \\lasp-store\home\taja6898\Documents\Mars_Data\Global_demo_parameters\TEST02_D2300.IMG
          # - [0.005, 0.008, 0.011, 0.014, 0.017, 0.02, 0.023, 0.026, 0.029, 0.032]
          - [60p, 70p, 80p]
      masks: {}
    pipeline:
      - task: majority
        iterations: 2
      # - task: boundary
      #   iterations: 2
      #   size: 3
      - task: sieve
        iterations: 1
      - task: open
        iterations: 1
    vectorization:
      driver: ESRI Shapefile # "pandas", "ESRI Shapefile", GeoJSON
      # simplify: 200
      colormap: Blues
      stats: ["area", "mean", "std", "min", "max"]
      output_dict: \\lasp-store\home\taja6898\Documents\Code\mineral-mapping\outputs
      base: 
        show: True
  
  D2300:
    name: D2300_yaml
    path: # \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters
    parameters:
      D2300:
        # path: \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_D2300.IMG
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_BAL1_EQU_IMP_D2300.IMG
        # path: \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_BAL1_EQU_IMP_D2300_MOS_IMP.IMG
        # - \\lasp-store\home\taja6898\Documents\Mars_Data\Global_demo_parameters\TEST02_D2300.IMG
        # - [0.005, 0.0075, 0.01, 0.0125, 0.015, 0.0175, 0.02, 0.0225, 0.025, 0.0275]
        # - [0.0075, 0.0175, 0.0275]
        thresholds: [0.005, 0.0125, 0.02, 0.0275] # what ran on the arcpy code
        # thresholds: [75p, 85p, 95p]
        # - [0.0275]
        median:
          iterations: 1

    masks: 
      pixel_guide:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_NSP_EQU_IMP_D2300_GID.IMG
        thresholds: [1]
        keep_shape: True # will be applied after processing pipeline

    pipeline:
      - task: majority
        iterations: 1
      # - task: boundary
      #   iterations: 1
        size: 3
      - task: sieve
        iterations: 1
      # - task: open
      #   iterations: 1
    vectorization:
      driver: ESRI Shapefile # "pandas", "ESRI Shapefile", GeoJSON, GPKG
      cs: GCS # PCS or GCS or any wkt/proj4
      simplify: 0
      # stats: ["area", "mean", "std", "5p", '25p', 'median', '75p', "95p"]
      stats: ["area", "mean", "std", '25p', 'median', '75p',]
      colormap: Blues # matplotlib colormap
      output_dict: \\lasp-store\home\taja6898\Documents\Code\vectroscopy\outputs
      base: 
        show: True
        stats: [] #["area", "mean", "std", "min", "max", '25p', '75p']
  
  TESTING:
    name: G2_D2300_TEST_DELIVERY_4
    path:
    parameters:
      D2300:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_BAL1_EQU_IMP_D2300_MOS_IMP.IMG #\\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_BAL1_EQU_IMP_D2300.IMG
        # path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_BAL1_EQU_IMP_D2300.IMG
        median:
          iterations: 1
        thresholds: [0.005, 0.01, 0.015, 0.02, 0.025]
        operator: '>'
  
    masks:
      pixel_guide:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_NSP_EQU_IMP_D2300_GID_MOS_IMP.IMG #\\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_NSP_EQU_IMP_D2300_GID.IMG
        # path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_NSP_EQU_IMP_D2300_GID.IMG
        thresholds: [1]
        operator: '='
        keep_shape: True # will be applied after processing pipeline

    pipeline:
      - task: majority
        iterations: 1
      # - task: boundary
      #   iterations: 1
      #   size: 3
      - task: sieve
        iterations: 1
      # - task: open
      #   iterations: 1

    vectorization:
      driver: GeoJSON 
      cs: GCS
      simplify: 0
      stats: ["area", "mean", "std", "5p", '25p', 'median', '75p', "95p"]
      color: cyan
      output_dict: \\lasp-store\home\taja6898\Documents\Code\mineral-mapping\outputs
      stack: False
      base: 
        show: True
        stats: []

  TESTING_INDIC:
    name: G2_PolySulfates_TEST_DELIVERY2
    path:
    parameters:
      BD1900_2:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_BAL1_EQU_IMP_BD1900_2_MOS_IMP.IMG
        thresholds: [0.012, 0.015, 0.017]
        median:
          iterations: 1

      SINDEX2:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_BAL1_EQU_IMP_BD1900_2_MOS_IMP.IMG
        thresholds: [0.01, 0.015, 0.02]
        median:
          iterations: 1
    masks:
      BD1500_2:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_BAL1_EQU_IMP_BD1500_2_MOS_IMP.IMG
        thresholds: [0.005]
        median:
          iterations: 1

      BD2100_2:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_BAL1_EQU_IMP_BD2100_2_MOS_IMP.IMG
        thresholds: [0.01]
        median:
          iterations: 1
      
      BD1900_2_mask:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_NSP_EQU_IMP_BD1900_2_GID_MOS_IMP.IMG
        thresholds: [1]
        keep_shape: True

      SINDEX2_mask:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_NSP_EQU_IMP_SINDEX2_GID_MOS_IMP.IMG
        thresholds: [1]
        keep_shape: True

      BD1500_2_mask:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_NSP_EQU_IMP_BD1500_2_GID_MOS_IMP.IMG
        thresholds: [1]
        keep_shape: True

      BD2100_2_mask:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_NSP_EQU_IMP_BD2100_2_GID_MOS_IMP.IMG
        thresholds: [1]
        keep_shape: True

    pipeline:
      - task: majority
        iterations: 1
      # - task: boundary
      #   iterations: 1
      #   size: 3
      - task: sieve
        iterations: 1
      # - task: open
      #   iterations: 1

    vectorization:
      driver: GeoJSON #GeoJSON 
      cs: GCS
      simplify: 0
      stats: ["area", "mean", "std", "5p", '25p', 'median', '75p', "95p"]
      color: violet #cyan
      output_dict: \\lasp-store\home\taja6898\Documents\Code\mineral-mapping\outputs
      stack: False
      base: 
        show: True
        stats: []

  TESTING_INDIC_MC:
    name: MC13_PolySulfates_7_24
    path:
    parameters:
      BD1900_2:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_BAL1_EQU_IMP_BD1900_2.IMG
        thresholds: [0.012, 0.015, 0.017]
        median:
          iterations: 1

      SINDEX2:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_BAL1_EQU_IMP_SINDEX2.IMG
        thresholds: [0.01, 0.015, 0.02]
        median:
          iterations: 1
    masks:
      BD1500_2:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_BAL1_EQU_IMP_BD1500_2.IMG
        thresholds: [0.005]
        median:
          iterations: 1

      BD2100_2:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_BAL1_EQU_IMP_BD2100_2.IMG
        thresholds: [0.01]
        median:
          iterations: 1
      
      BD1900_2_mask:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_NSP_EQU_IMP_BD1900_2_GID.IMG
        thresholds: [1]
        keep_shape: True

      SINDEX2_mask:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_NSP_EQU_IMP_SINDEX2_GID.IMG
        thresholds: [1]
        keep_shape: True

      BD1500_2_mask:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_NSP_EQU_IMP_BD1500_2_GID.IMG
        thresholds: [1]
        keep_shape: True

      BD2100_2_mask:
        path: \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_NSP_EQU_IMP_BD2100_2_GID.IMG
        thresholds: [1]
        keep_shape: True

    pipeline:
      - task: majority
        iterations: 1
      # - task: boundary
      #   iterations: 1
      #   size: 3
      - task: sieve
        iterations: 1
      # - task: open
      #   iterations: 1

    vectorization:
      driver: ESRI Shapefile #GeoJSON 
      cs: GCS
      simplify: 0
      stats: ["area", "mean", "std", "5p", '25p', 'median', '75p', "95p"]
      color: violet #cyan
      output_dict: \\lasp-store\home\taja6898\Documents\Code\vectroscopy\outputs
      stack: True
      base: 
        show: True
        stats: []