processes:
  default:
    name: 
    thresholds:
      path: 
      median:
        size: 3
        iterations: 1 
      parameters:
      masks:
    pipeline:
      - task: majority
        iterations: 1
      # - task: boundary
      #   iterations: 1
      - task: sieve
        iterations: 1
      # - task: open
      #   iterations: 1
    vectorization:
      driver: pandas
      colormap: 
      stats: ["count", "mean", "std", "min", "max", "median", "75p", "25p"]
      output_dict: 
      base: 
        show: True
        stats: False