processes:
  parameterization: 
    name: D2300
    path: \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters # Can be file or directory
    thresholds:
      median:
        run: True
        size: 3
        iterations: 1
      parameters:
        D2300: [0.005, 0.0075, 0.01, 0.0125, 0.015, 0.0175, 0.02, 0.0225, 0.025, 0.0275]
      masks:
    pipeline:
    - task: majority
      iterations: 1

    - task: boundary
      iterations: 1

    - task: majority
      iterations: 3

    - task: sieve
      iterations: 1

    - task: boundary
      iterations: 1
    
    vectorization:
      stats: ["avg", "min", "max", "std"]
      driver: SHP
      output_dict: \\lasp-store\home\taja6898\Documents\Code\mineral-mapping\outputs

  Indicator:
    name: FeMgSmectite
    path: \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters 
    thresholds:
      median:
        run: True
        size: 3
        iterations: 1
      parameters:
        D2300: [0.001, 0.005, 0.01]
        BD1900_2: [0.01, 0.015, 0.02]
      masks:
        BD1500_2: [0.005]
    pipeline:
    - task: majority
      iterations: 1

    - task: boundary
      iterations: 1

    - task: majority
      iterations: 3

    - task: sieve
      iterations: 1

    - task: boundary
      iterations: 1
    
    vectorization:
      driver: SHP
      output_dict: \\lasp-store\home\taja6898\Documents\Code\mineral-mapping\outputs

# PROCESSING_FUNCTIONS = {
#     "median": apply_median_filter,
#     "thresholds": apply_thresholds,
#     "masks": apply_masks,
#     "majority": apply_majority_filter,
#     "boundary": apply_boundary_smooth,
#     "sieve": apply_sieve_filter,
# }
# General workflow:
#   - read data
#   - meadian filter
#   - apply thresholds
#   - generalization
#   - vectorization


    # processessing:
    #   median:
    #     size: 3
    #     iterations: 1
    #   thresholds: 
    #     BD1500_2: [0.005, 0.0065, 0.008, 0.0095, 0.011, 0.0125, 0.014, 0.0155, 0.017, 0.0185]
    #   masks:
  
    #   majority:
    #     size: 3
    #     iterations: 1
    #   boundary:
    #     size: 3
    #     iterations: 1
    #   majority1:
    #     size: 3
    #     iterations: 1
    #   sieve:
    #     size: 3
    #     iterations: 1
    #   boundary1:
    #     size: 3
    #     iterations: 1