processes:
  Indicator:
    name: FeMgSmectite
    path: # \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters 
    thresholds:
      median:
        run: True
        size: 3
        iterations: 1
      parameters:
        D2300:
        - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_D2300.IMG
        - [0.001, 0.005, 0.01]
        BD1900_2: 
        - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_BD1900_2.IMG 
        - [0.01, 0.015, 0.02]
      masks:
        BD1500_2: 
        - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_BD1500_2.IMG 
        - [0.005]
    pipeline:
    - task: majority
      iterations: 4

    - task: sieve
      iterations: 1
    
    vectorization:
      driver: SHP
      output_dict: \\lasp-store\home\taja6898\Documents\Code\mineral-mapping\outputs
  
  Parameter:
    name: T1250_D2300_with_color
    path: # \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters 
    thresholds:
      median:
        run: True
        size: 3
        iterations: 1
      parameters:
        D2300:
        - \\lasp-store\home\taja6898\Documents\Mars_Data\T1250_demo_parameters\T1250_cdodtot_BAL1_D2300.IMG
        # - \\lasp-store\home\taja6898\Documents\Mars_Data\MC13_demo_parameters\MC13_BAL1_EQU_IMP_D2300.IMG
        # - \\lasp-store\home\taja6898\Documents\Mars_Data\LatitudeBands_demo_parameters\MC_789ABCDEFGHIJKLM_BAL1_EQU_IMP_D2300_MOS_IMP.IMG
        - [0.005, 0.0125, 0.02, 0.0275]
      masks:
    pipeline:
    - task: majority
      iterations: 4

    - task: sieve
      iterations: 1
    
    vectorization:
      driver: geojson # "geojson", "pandas", "ESRI Shapefile", GeoJSON
      output_dict: \\lasp-store\home\taja6898\Documents\Code\mineral-mapping\outputs


























# PROCESSING_FUNCTIONS = {
#     "median": apply_median_filter,
#     "thresholds": apply_thresholds,
#     "masks": apply_masks,
#     "majority": apply_majority_filter,
#     "boundary": apply_boundary_smooth,
#     "sieve": apply_sieve_filter,
# }
# General workflow:
#   - read data
#   - meadian filter
#   - apply thresholds
#   - generalization
#   - vectorization


    # processessing:
    #   median:
    #     size: 3
    #     iterations: 1
    #   thresholds: 
    #     BD1500_2: [0.005, 0.0065, 0.008, 0.0095, 0.011, 0.0125, 0.014, 0.0155, 0.017, 0.0185]
    #   masks:
  
    #   majority:
    #     size: 3
    #     iterations: 1
    #   boundary:
    #     size: 3
    #     iterations: 1
    #   majority1:
    #     size: 3
    #     iterations: 1
    #   sieve:
    #     size: 3
    #     iterations: 1
    #   boundary1:
    #     size: 3
    #     iterations: 1